(define (problem MAPF_config)
    (:domain MAPF)
    (:requirements :strips)
    (:objects
        agent1 agent2 vertex1 vertex2 vertex3 vertex4 vertex5 vertex6 vertex7 vertex8
    )
    (:init
        (agent agent1)
        (agent agent2)

        (vertex vertex1)
        (vertex vertex2)
        (vertex vertex3)
        (vertex vertex4)
        (vertex vertex5)
        (vertex vertex6)
        (vertex vertex7)
        (vertex vertex8)

        (agent-on-vertex agent1 vertex1)
        (agent-on-vertex agent2 vertex2)

        (vertex-empty vertex3)
        (vertex-empty vertex4)
        (vertex-empty vertex5)
        (vertex-empty vertex6)
        (vertex-empty vertex7)
        (vertex-empty vertex8)

        (distinct vertex1 vertex2)
        (distinct vertex1 vertex3)
        (distinct vertex1 vertex4)
        (distinct vertex1 vertex5)
        (distinct vertex1 vertex6)
        (distinct vertex1 vertex7)
        (distinct vertex1 vertex8)
        (distinct vertex2 vertex3)
        (distinct vertex2 vertex4)
        (distinct vertex2 vertex5)
        (distinct vertex2 vertex6)
        (distinct vertex2 vertex7)
        (distinct vertex2 vertex8)
        (distinct vertex3 vertex4)
        (distinct vertex3 vertex5)
        (distinct vertex3 vertex6)
        (distinct vertex3 vertex7)
        (distinct vertex3 vertex8)
        (distinct vertex4 vertex5)
        (distinct vertex4 vertex6)
        (distinct vertex4 vertex7)
        (distinct vertex4 vertex8)
        (distinct vertex5 vertex6)
        (distinct vertex5 vertex7)
        (distinct vertex5 vertex8)
        (distinct vertex6 vertex7)
        (distinct vertex6 vertex8)
        (distinct vertex7 vertex8)

        (neighbor-vertexes vertex1 vertex2)
        ;(neighbor-vertexes vertex1 vertex3)
        ;(neighbor-vertexes vertex1 vertex4)
        ;(neighbor-vertexes vertex1 vertex5)
        ;(neighbor-vertexes vertex1 vertex6)
        ;(neighbor-vertexes vertex1 vertex7)
        ;(neighbor-vertexes vertex1 vertex8)
        (neighbor-vertexes vertex2 vertex3)
        (neighbor-vertexes vertex2 vertex4)
        (neighbor-vertexes vertex2 vertex5)
        ;(neighbor-vertexes vertex2 vertex6)
        ;(neighbor-vertexes vertex2 vertex7)
        ;(neighbor-vertexes vertex2 vertex8)
        (neighbor-vertexes vertex3 vertex4)
        (neighbor-vertexes vertex3 vertex5)
        (neighbor-vertexes vertex3 vertex6)
        ;(neighbor-vertexes vertex3 vertex7)
        ;(neighbor-vertexes vertex3 vertex8)
        (neighbor-vertexes vertex4 vertex5)
        (neighbor-vertexes vertex4 vertex6)
        (neighbor-vertexes vertex4 vertex7)
        ;(neighbor-vertexes vertex4 vertex8)
        (neighbor-vertexes vertex5 vertex6)
        (neighbor-vertexes vertex5 vertex7)
        (neighbor-vertexes vertex5 vertex8)
        (neighbor-vertexes vertex6 vertex7)
        ;(neighbor-vertexes vertex6 vertex8)
        (neighbor-vertexes vertex7 vertex8)
    )

    (:goal( and
            (agent-on-vertex agent1 vertex6)
            (agent-on-vertex agent2 vertex8)
        )
    )
)